### ISSUE TITLE
sys vs _sys

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt#18]
Don't we want to `import sys as _sys`?

**Comment by mottosso** [comment]
Why?

**Comment by fredrikaverpil** [comment]
I'm just thinking consistency. Since all functions are prefixed with `_`, why not also make sure everything else is?

Or perhaps that's not standard procedure?

To be honest, I'm not sure why you wanted the prefix for the functions, as the module is being replaced at `sys.modules["Qt"] = binding()` anyways.

**Comment by mottosso** [comment]
Underscore prefix is convention for "private" members; that is, members that isn't part of an interface, in this case from the importer of the module.

You're right, it technically won't matter because it's being replaced, but it's more to communicate to whomever reads the code that these are implementation detail, and not interface.

When we *do* have functions that *are* meant to be used from the importer, then those would *not* have an underscore and the reader could gather than "aha, I can rely on these members to remain consistent, versioned and backwards compatible when this interface changes". The same is not true for the ones with an underscore.

Importing modules into a module with an underscore would make sense from a technical point of view, because they would otherwise be part of the outside interface. But on the other hand it makes the code itself less readable so there's a tradeoff to be made in readability.

**Comment by fredrikaverpil** [comment]
Ok, that's fair. Figured I'd just bring it up. :)

**Comment by mottosso** [comment]
It's good that you do. :) I take a lot of stuff for granted, so it can be healthy to sometimes shine a light on things in case they are based on some shenanigans. Hopefully this makes sense though, it's worked well long-term and I read a lot of code in other projects that follow the same convention.
