### ISSUE TITLE
Remove init()?

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt#6]
`init()` is being declared and immediately called, might as well not be a function?

**Comment by fredrikaverpil** [comment]
I'd be curious on what's the norm here, perhaps there's a PEP for this?

Either way, it's not a biggie.

**Comment by mottosso** [comment]
Possibly, it would be related to importing modules with "side-effects", because that's what it is.

To me it's just unintuitive, because it looks like functions you can call, but then it calls it implicitly. Each of those functions should be prefixed with an `_` if we are going super clean. All of that is implementation detail and should never be called (or accessible) from the outside and I think it would be a good idea to communicate that.

**Comment by fredrikaverpil** [comment]
Agreed.

So there is no such thing as an `_init()` or something like that, which is actually called automatically, right?
I mean, something like a `main()`.
If not, I'm all for just removing that function and placing the code at the bottom, and adressing https://github.com/mottosso/Qt/issues/9 at the same time.

**Comment by fredrikaverpil** [comment]
I think we should close this issue. Ok?

**Comment by mottosso** [comment]
Yes, at this point, there is a reason we have a function and call it immediately; so that it can either return or throw an exception.
